development:
  type: http
  url: http://neo4j:password@localhost:7474

test:
  type: http
  url: http://neo4j:password@localhost:7575'

production:
  type: http
  url: <%= ENV.fetch('GRAPHENEDB_URL', nil) %>
